source "http://rubygems.org"

gem "wisper"
gem "pqueue"
gem "celluloid"
gem "lawyer"
gem "gosu"

group :development do
  gem "shoulda", ">= 0"
  gem "shoulda-context"
  gem "rdoc", "~> 3.12"
  gem "bundler", "~> 1.0"
  gem "jeweler", "~> 2.0.1"
  gem "simplecov", ">= 0"
  gem "test-unit"
  gem "pry"
  gem "mocha"
  gem "guard"
  gem "guard-rake"
  gem "guard-shell"
  gem "ruby-prof"
  gem "rubocop"
  gem "flog"
end
